### ISSUE TITLE
Missing Semigroup instance for Traversed

### ISSUE THREAD

**Issue by TerrorJack** [aelve/microlens#96]
In upcoming `base-4.11`, `Semigroup` is a superclass of `Monoid`. Thus compiling `microlens-0.4.8.1` with ghc head results in following error:

```
--  While building package microlens-0.4.8.1 using:
      C:\Users\astro\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.1.0.0_ghc-8.5.20171205.exe --builddir=.stack-work\dist\50875de6 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\astro\haskell\asterius\.stack-work\logs\microlens-0.4.8.1.log

    Configuring microlens-0.4.8.1...
    Preprocessing library for microlens-0.4.8.1..
    Building library for microlens-0.4.8.1..
    [1 of 4] Compiling Lens.Micro.Type  ( src\Lens\Micro\Type.hs, .stack-work\dist\50875de6\build\Lens\Micro\Type.o )
    [2 of 4] Compiling Lens.Micro.Internal ( src\Lens\Micro\Internal.hs, .stack-work\dist\50875de6\build\Lens\Micro\Internal.o )
    [3 of 4] Compiling Lens.Micro       ( src\Lens\Micro.hs, .stack-work\dist\50875de6\build\Lens\Micro.o )

    C:\Users\astro\AppData\Local\Temp\stack9124\microlens-0.4.8.1\src\Lens\Micro.hs:1273:10: error:
        * Could not deduce (Semigroup (Traversed a f))
            arising from the superclasses of an instance declaration
          from the context: Applicative f
            bound by the instance declaration at src\Lens\Micro.hs:1273:10-48
        * In the instance declaration for `Monoid (Traversed a f)'
         |
    1273 | instance Applicative f => Monoid (Traversed a f) where
         |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by neongreen** [comment]
I've just released

* microlens-0.4.8.2
* microlens-th-0.4.1.2
* microlens-mtl-0.1.11.1

which compile with GHC 7.4.1 (thanks to @deepfire!)
