### PR TITLE
Traversed:  add Semigroup instance (GHC 8.4 compat)

### LINKED ISSUE #96: Missing Semigroup instance for Traversed
In upcoming `base-4.11`, `Semigroup` is a superclass of `Monoid`. Thus compiling `microlens-0.4.8.1` with ghc head results in following error:

```
--  While building package microlens-0.4.8.1 using:
      C:\Users\astro\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.1.0.0_ghc-8.5.20171205.exe --builddir=.stack-work\dist\50875de6 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\astro\haskell\asterius\.stack-work\logs\microlens-0.4.8.1.log

    Configuring microlens-0.4.8.1...
    Preprocessing library for microlens-0.4.8.1..
    Building library for microlens-0.4.8.1..
    [1 of 4] Compiling Lens.Micro.Type  ( src\Lens\Micro\Type.hs, .stack-work\dist\50875de6\build\Lens\Micro\Type.o )
    [2 of 4] Compiling Lens.Micro.Internal ( src\Lens\Micro\Internal.hs, .stack-work\dist\50875de6\build\Lens\Micro\Internal.o )
    [3 of 4] Compiling Lens.Micro       ( src\Lens\Micro.hs, .stack-work\dist\50875de6\build\Lens\Micro.o )

    C:\Users\astro\AppData\Local\Temp\stack9124\microlens-0.4.8.1\src\Lens\Micro.hs:1273:10: error:
        * Could not deduce (Semigroup (Traversed a f))
            arising from the superclasses of an instance declaration
          from the context: Applicative f
            bound by the instance declaration at src\Lens\Micro.hs:1273:10-48
        * In the instance declaration for `Monoid (Traversed a f)'
         |
    1273 | instance Applicative f => Monoid (Traversed a f) where
         |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by deepfire**
Tested to work on GHC 8.4 snapshot, as of today.  Fixes #96.  Also tested on GHC 8.0.2 and 7.10.3.

### CODE REVIEW

**Comment by deepfire** [comment]
CI failure looks unrelated.

**Comment by deepfire** [comment]
Updated for a warning-freedom, and a lighter approach.

**Comment by deepfire** [comment]
cc @neongreen

**Comment by deepfire** [comment]
Also fixes `microlens-mtl` now..

**Comment by neongreen** [comment]
Thanks!
